RIGVEDA_CACHE_SIZE = 1024
POLLING_MAX_LIMIT = 100
CRAWLING_PERIOD = 3 # in seconds

MONGODB_DATABASE = "tracker"
MONGODB_HOST = "localhost"
MONGODB_PORT = 27017

REDIS_HOST = "localhost"
REDIS_PORT = 6379

GOOGLE_API_KEY = "AIzaSyCksKXPienmrnpoH7iDzUnDMjJy9CtS7eI"

GCM_COLLAPSE_KEY = "article_pub"
